name: Generate Snake

on:
  push:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ab2gbl
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
      - name: Push to output branch
        uses: CasperWA/push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_branch: "main"
          destination_owner: ${{ github.repository_owner }}
          destination_repo: ${{ github.repository_owner }}
          destination_branch: "output"
          destination_folder: "dist"
          commit_message: "Update github-contribution-grid-snake"
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

      - name: Update README
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update README with snake"
          title: "Update README with snake"
          body: "Update README with snake"
          branch: "update-readme-with-snake"
          delete-branch: true
          labels: automated pr
          base: main
          branch-suffix: random
          add-paths: README.md
          source-repository: ${{ github.repository_owner }}/${{ github.repository_owner }}
          destination-repository: ${{ github.repository_owner }}/${{ github.repository_owner }}
          destination-branch: "main"
          file-content: |
            <picture>
            <source media="(prefers-color-scheme: dark)" srcset="dist/github-contribution-grid-snake-dark.svg">
            <img alt="github-snake" src="dist/github-contribution-grid-snake.svg">
            </picture>
          file-path: "README.md"
