name: Generate GitHub Snake

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main
      
permissions:
  contents: write # This grants write access to repository contents

jobs:
  build:
    name: Generate Snake SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ab2gbl # Replace with your GitHub username
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is automatically provided by GitHub Actions
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output # This is a temporary branch to store the generated files
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
